# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='learn_time_2',
            field=models.IntegerField(default=1, verbose_name='\u5b66\u4e60\u65f6\u957f(\u5206\u949f)'),
        ),
    ]
